# Generated by Django 5.1.5 on 2026-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('metric', models.CharField(max_length=32, verbose_name='المقياس')),
                ('dimension', models.CharField(blank=True, max_length=120, verbose_name='البُعد')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'إحصائية يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'metric', 'dimension'), name='unique_daily_stat')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='المسار')),
                ('locale', models.CharField(blank=True, max_length=5, verbose_name='اللغة')),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='نوع المحتوى')),
                ('object_slug', models.CharField(blank=True, max_length=220, verbose_name='معرّف العنصر')),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='مصدر الزيارة')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='الدولة')),
                ('device_type', models.CharField(choices=[('mobile', 'هاتف'), ('tablet', 'لوحي'), ('desktop', 'سطح مكتب'), ('bot', 'زاحف')], default='desktop', max_length=10, verbose_name='الجهاز')),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='بصمة الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'مشاهدة صفحة',
                'verbose_name_plural': 'مشاهدات الصفحات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'content_type'], name='analytics_p_created_5f49a7_idx'), models.Index(fields=['created_at', 'referrer_domain'], name='analytics_p_created_930282_idx')],
            },
        ),
    ]
