databases:
  - name: nexa-db
    plan: free
    databaseName: nexa
    user: nexa

services:
  - type: web
    name: nexa
    runtime: docker
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: stingdev.pro,www.stingdev.pro,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://stingdev.pro,https://www.stingdev.pro
      - key: DB_ENGINE
        value: postgres
      - key: DB_NAME
        fromDatabase:
          name: nexa-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nexa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nexa-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: nexa-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nexa-db
          property: port
      - key: FRONTEND_URL
        value: https://stingdev.pro
      - key: REVALIDATE_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "True"
      - key: COOKIE_SAMESITE
        value: Lax
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: "NEXA SYSTEMS <no-reply@stingdev.pro>"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: NEXT_PUBLIC_SITE_URL
        value: https://stingdev.pro
      - key: NEXT_PUBLIC_API_URL
        value: /api/v1
      - key: INTERNAL_API_URL
        value: http://127.0.0.1:8000/api/v1
      - key: BACKEND_ORIGIN
        value: http://127.0.0.1:8000
