[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
pythonpath = .
python_files = test_*.py
testpaths = tests
addopts = -q --strict-markers --durations=5
filterwarnings =
    ignore::DeprecationWarning
