# Generated by Django 5.1.5 on 2026-07-30 22:18

import apps.core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_request', 'طلب مشروع'), ('contact_message', 'رسالة تواصل'), ('new_member', 'عضو جديد'), ('new_comment', 'تعليق جديد'), ('comment_report', 'بلاغ عن تعليق'), ('new_subscriber', 'مشترك جديد'), ('email_failed', 'فشل إرسال بريد'), ('follow_up_due', 'موعد متابعة'), ('post_in_review', 'مقال بانتظار المراجعة'), ('comment_reply', 'رد على تعليقك'), ('system', 'نظام')], db_index=True, max_length=32, verbose_name='النوع')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('message_ar', models.TextField(blank=True, verbose_name='النص (عربي)')),
                ('message_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='الرابط')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='النموذج')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف الكائن')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('recipient', models.ForeignKey(blank=True, help_text='فارغ = لكل مستخدمي لوحة التحكم', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستقبِل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
    ]
