# Generated by Django 5.1.5 on 2026-09-25 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='المفتاح العام')),
                ('private_pem', models.TextField(verbose_name='المفتاح الخاص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مفاتيح الإشعارات',
                'verbose_name_plural': 'مفاتيح الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='عنوان الاشتراك')),
                ('p256dh', models.CharField(max_length=200, verbose_name='مفتاح التشفير')),
                ('auth', models.CharField(max_length=100, verbose_name='مفتاح المصادقة')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفعيل')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك إشعارات',
                'verbose_name_plural': 'اشتراكات الإشعارات',
            },
        ),
    ]
