# Generated by Django 5.1.5 on 2026-07-31 15:17

import apps.core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مُفعّل')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='المعرّف')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('color', models.CharField(blank=True, max_length=9, verbose_name='اللون')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['display_order', 'name_ar'],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=60, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=60, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='المعرّف')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد الاستخدامات')),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'الوسوم',
                'ordering': ['-usage_count', 'name_ar'],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد المشاهدات')),
                ('seo_title_ar', models.CharField(blank=True, max_length=160, verbose_name='عنوان SEO (عربي)')),
                ('seo_title_en', models.CharField(blank=True, max_length=160, verbose_name='عنوان SEO (إنجليزي)')),
                ('seo_description_ar', models.TextField(blank=True, max_length=320, verbose_name='وصف SEO (عربي)')),
                ('seo_description_en', models.TextField(blank=True, max_length=320, verbose_name='وصف SEO (إنجليزي)')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='نص البحث')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='المعرّف')),
                ('excerpt_ar', models.TextField(blank=True, max_length=400, verbose_name='الملخص (عربي)')),
                ('excerpt_en', models.TextField(blank=True, max_length=400, verbose_name='الملخص (إنجليزي)')),
                ('content_ar', models.TextField(blank=True, verbose_name='المحتوى (عربي)')),
                ('content_en', models.TextField(blank=True, verbose_name='المحتوى (إنجليزي)')),
                ('reading_time_ar', models.PositiveSmallIntegerField(default=0, verbose_name='وقت القراءة (عربي)')),
                ('reading_time_en', models.PositiveSmallIntegerField(default=0, verbose_name='وقت القراءة (إنجليزي)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_review', 'قيد المراجعة'), ('scheduled', 'مجدول'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النشر')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='مميز')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='يسمح بالتعليقات')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='التصنيف')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediafile', verbose_name='صورة الغلاف')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediafile', verbose_name='صورة المشاركة')),
                ('related_posts', models.ManyToManyField(blank=True, to='blog.post', verbose_name='مقالات مرتبطة')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('publish_post', 'نشر المقالات')],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='blog.post', verbose_name='المقال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL, verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'مقال محفوظ',
                'verbose_name_plural': 'المقالات المحفوظة',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_saved_post')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'),
        ),
    ]
