# Generated by Django 5.1.5 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(blank=True, max_length=60, verbose_name='الاسم (عربي)'),
        ),
    ]
