# Generated by Django 5.1.5 on 2026-07-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'صلاحية نظام',
                'verbose_name_plural': 'صلاحيات النظام',
                'permissions': [('manage_settings', 'إدارة إعدادات الموقع'), ('manage_seo', 'إدارة إعدادات SEO'), ('view_analytics', 'عرض التحليلات'), ('view_auditlog_full', 'عرض سجل التدقيق الكامل'), ('manage_users', 'إدارة المستخدمين والأدوار'), ('manage_media', 'إدارة مكتبة الوسائط')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('old_path', models.CharField(max_length=255, unique=True, verbose_name='المسار القديم')),
                ('new_path', models.CharField(max_length=255, verbose_name='المسار الجديد')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 دائم'), (302, '302 مؤقت')], default=301, verbose_name='رمز الحالة')),
                ('hits', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد الاستخدامات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مُفعّل')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('publish', 'نشر'), ('unpublish', 'إلغاء نشر'), ('login', 'تسجيل دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة المرور'), ('password_reset', 'استعادة كلمة المرور'), ('email_verified', 'تأكيد البريد'), ('account_deleted', 'حذف حساب'), ('export', 'تصدير')], db_index=True, max_length=32, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='النموذج')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='معرّف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='متصفح المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx')],
            },
        ),
    ]
