# Generated by Django 5.1.5 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processstep_sociallink_stat_faq_seosettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(blank=True, verbose_name='الإجابة (عربي)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='السؤال (عربي)'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='key',
            field=models.CharField(blank=True, choices=[('hero', 'الواجهة'), ('intro', 'نبذة مختصرة'), ('stats', 'الإحصائيات'), ('services', 'الخدمات الرئيسية'), ('solutions', 'الحلول حسب القطاعات'), ('projects', 'المشاريع المميزة'), ('case_studies', 'دراسات الحالة'), ('process', 'طريقة العمل'), ('technologies', 'التقنيات'), ('testimonials', 'شهادات العملاء'), ('posts', 'أحدث المقالات'), ('newsletter', 'النشرة البريدية'), ('cta', 'دعوة للتواصل')], max_length=32, verbose_name='المفتاح'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف (عربي)'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='title_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='العنوان (عربي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_ar',
            field=models.CharField(blank=True, default='stingdev', max_length=120, verbose_name='اسم الموقع (عربي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, default='stingdev', max_length=120, verbose_name='اسم الموقع (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'البريد'), ('other', 'أخرى')], max_length=20, verbose_name='المنصة'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, max_length=300, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label_ar',
            field=models.CharField(blank=True, max_length=80, verbose_name='التسمية (عربي)'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(blank=True, max_length=20, verbose_name='القيمة'),
        ),
    ]
