# Generated by Django 5.1.5 on 2026-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_faq_answer_ar_alter_faq_question_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_ar',
            field=models.CharField(blank=True, default='نيكسا سيستمز', max_length=120, verbose_name='اسم الموقع (عربي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, default='NEXA SYSTEMS', max_length=120, verbose_name='اسم الموقع (إنجليزي)'),
        ),
    ]
