# Generated by Django 5.1.5 on 2026-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rebrand_nexa_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_ar',
            field=models.CharField(blank=True, default='ستينج سيستم', max_length=120, verbose_name='اسم الموقع (عربي)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, default='StingSystem', max_length=120, verbose_name='اسم الموقع (إنجليزي)'),
        ),
    ]
