# Generated by Django 5.1.5 on 2026-09-23 22:43

from django.db import migrations, models
from django.db.models import F


def add_faq_section(apps, schema_editor):
    """ينشئ قسم الأسئلة الشائعة في الرئيسية قبل الدعوة للتواصل مباشرة.

    الأقسام لا تُنشأ من اللوحة، فبدون هذا لا يظهر القسم في المواقع
    القائمة. يُنشأ مرة واحدة فقط ولا يمس الأقسام الأخرى إلا بإزاحة ما
    بعد موضعه خطوة واحدة. يختفي تلقائيًا ما دامت لا توجد أسئلة مفعّلة.
    """
    PageSection = apps.get_model("core", "PageSection")
    if PageSection.objects.filter(page="home", key="faq").exists():
        return
    home = PageSection.objects.filter(page="home")
    if not home.exists():
        # قاعدة جديدة: seed_content ينشئ الأقسام كلها بترتيبها
        return

    cta = home.filter(key="cta").first()
    if cta is not None:
        position = cta.display_order
        home.filter(display_order__gte=position).update(display_order=F("display_order") + 1)
    else:
        position = (home.order_by("-display_order").first().display_order or 0) + 1

    PageSection.objects.create(
        page="home",
        key="faq",
        title_ar="أسئلة شائعة",
        title_en="Frequently asked questions",
        display_order=position,
        config={"limit": 6},
        is_visible=True,
        auto_hide_when_empty=True,
    )


def remove_faq_section(apps, schema_editor):
    apps.get_model("core", "PageSection").objects.filter(page="home", key="faq").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_site_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='key',
            field=models.CharField(blank=True, choices=[('hero', 'الواجهة'), ('intro', 'نبذة مختصرة'), ('stats', 'الإحصائيات'), ('services', 'الخدمات الرئيسية'), ('solutions', 'الحلول حسب القطاعات'), ('projects', 'المشاريع المميزة'), ('case_studies', 'دراسات الحالة'), ('process', 'طريقة العمل'), ('technologies', 'التقنيات'), ('testimonials', 'شهادات العملاء'), ('posts', 'أحدث المقالات'), ('newsletter', 'النشرة البريدية'), ('faq', 'أسئلة شائعة'), ('cta', 'دعوة للتواصل')], max_length=32, verbose_name='المفتاح'),
        ),
        migrations.RunPython(add_faq_section, remove_faq_section),
    ]
