# Generated by Django 5.1.5 on 2026-08-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_mediafile_original_name_alter_mediafolder_name'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issuer_ar',
            field=models.CharField(blank=True, max_length=140, verbose_name='الجهة المانحة (عربي)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name_ar',
            field=models.CharField(blank=True, max_length=180, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_ar',
            field=models.CharField(blank=True, max_length=140, verbose_name='الدرجة (عربي)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_ar',
            field=models.CharField(blank=True, max_length=140, verbose_name='المؤسسة (عربي)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization_ar',
            field=models.CharField(blank=True, max_length=140, verbose_name='الجهة (عربي)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_ar',
            field=models.CharField(blank=True, max_length=140, verbose_name='المسمى (عربي)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_ar',
            field=models.TextField(blank=True, max_length=400, verbose_name='وصف مختصر (عربي)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, max_length=160, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediafile', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title_ar',
            field=models.CharField(blank=True, max_length=180, verbose_name='العنوان (عربي)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=400, verbose_name='وصف مختصر (عربي)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ar',
            field=models.CharField(blank=True, max_length=160, verbose_name='العنوان (عربي)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, choices=[('language', 'لغة برمجة'), ('frontend', 'واجهة أمامية'), ('backend', 'واجهة خلفية'), ('mobile', 'موبايل'), ('desktop', 'سطح مكتب'), ('database', 'قواعد بيانات'), ('tool', 'أدوات')], db_index=True, max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=90, unique=True, verbose_name='المعرّف'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم العميل (عربي)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content_ar',
            field=models.TextField(blank=True, verbose_name='نص الشهادة (عربي)'),
        ),
    ]
