# Generated by Django 5.1.5 on 2026-09-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_mediafile_original_name_alter_mediafolder_name'),
        ('portfolio', '0002_alter_certification_issuer_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediafile', verbose_name='الشعار'),
        ),
    ]
