# Generated by Django 5.1.5 on 2026-09-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_technology_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='audience',
            field=models.JSONField(blank=True, default=list, verbose_name='لمن تناسب'),
        ),
        migrations.AddField(
            model_name='service',
            name='client_inputs',
            field=models.JSONField(blank=True, default=list, verbose_name='ما نحتاجه من العميل'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_approach_ar',
            field=models.TextField(blank=True, verbose_name='كيف تُحدَّد المدة والتكلفة (عربي)'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_approach_en',
            field=models.TextField(blank=True, verbose_name='كيف تُحدَّد المدة والتكلفة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='service',
            name='problem_ar',
            field=models.TextField(blank=True, verbose_name='المشكلة التي تعالجها (عربي)'),
        ),
        migrations.AddField(
            model_name='service',
            name='problem_en',
            field=models.TextField(blank=True, verbose_name='المشكلة التي تعالجها (إنجليزي)'),
        ),
    ]
