# Generated by Django 5.1.5 on 2026-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service_decision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_product',
            field=models.BooleanField(db_index=True, default=False, help_text='منتج تملكه ستينج سيستم وتديره، لا مشروع لعميل.', verbose_name='منتج نملكه'),
        ),
    ]
