# Generated by Django 5.1.5 on 2026-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_is_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('education', 'التعليم'), ('retail', 'التجارة والبقالات'), ('restaurants', 'المطاعم'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('real_estate', 'العقارات'), ('pharmacy', 'الصيدليات'), ('healthcare', 'الرعاية الصحية'), ('ngo', 'المنظمات'), ('logistics', 'المخزون والتوزيع'), ('hospitality', 'الفنادق والضيافة'), ('general', 'عام')], db_index=True, default='general', max_length=20, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sector',
            field=models.CharField(choices=[('education', 'التعليم'), ('retail', 'التجارة والبقالات'), ('restaurants', 'المطاعم'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('real_estate', 'العقارات'), ('pharmacy', 'الصيدليات'), ('healthcare', 'الرعاية الصحية'), ('ngo', 'المنظمات'), ('logistics', 'المخزون والتوزيع'), ('hospitality', 'الفنادق والضيافة'), ('general', 'عام')], db_index=True, default='general', max_length=20, verbose_name='القطاع'),
        ),
    ]
