# Generated by Django 5.1.5 on 2026-07-30 15:48

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='الصورة الشخصية')),
                ('role', models.CharField(choices=[('super_admin', 'مدير عام'), ('content_manager', 'مدير محتوى'), ('editor', 'محرر'), ('crm_manager', 'مدير علاقات العملاء'), ('marketing_manager', 'مدير تسويق'), ('member', 'عضو'), ('client', 'عميل')], db_index=True, default='member', max_length=32, verbose_name='الدور')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة المفضلة')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='البريد مؤكَّد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP للدخول')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='الشركة')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='المدينة')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='واتساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف عميل',
                'verbose_name_plural': 'ملفات العملاء',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='الرمز')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق بريد',
                'verbose_name_plural': 'رموز تحقق البريد',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=254, verbose_name='البريد')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='عنوان IP')),
                ('success', models.BooleanField(default=False, verbose_name='ناجحة')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'محاولة دخول',
                'verbose_name_plural': 'محاولات الدخول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_lo_email_f32d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bio_ar', models.TextField(blank=True, verbose_name='نبذة (عربي)')),
                ('bio_en', models.TextField(blank=True, verbose_name='نبذة (إنجليزي)')),
                ('website', models.URLField(blank=True, verbose_name='الموقع')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='المدينة')),
                ('newsletter_opt_in', models.BooleanField(default=False, verbose_name='مشترك في النشرة')),
                ('notify_on_comment_reply', models.BooleanField(default=True, verbose_name='إشعار عند الرد على تعليقي')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف عضو',
                'verbose_name_plural': 'ملفات الأعضاء',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='الرمز')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز استعادة كلمة مرور',
                'verbose_name_plural': 'رموز استعادة كلمة المرور',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
