# Generated by Django 5.1.5 on 2026-07-31 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='الشركة')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='واتساب')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='المدينة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('client_since', models.DateField(default=django.utils.timezone.now, verbose_name='عميل منذ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('projects', models.ManyToManyField(blank=True, related_name='clients', to='portfolio.project', verbose_name='المشاريع')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_client', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='الشركة')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='واتساب')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='المدينة')),
                ('source', models.CharField(choices=[('website_form', 'نموذج طلب مشروع'), ('contact_form', 'نموذج تواصل'), ('whatsapp', 'واتساب'), ('referral', 'توصية'), ('social', 'وسائل التواصل'), ('direct', 'مباشر'), ('other', 'أخرى')], db_index=True, default='website_form', max_length=20, verbose_name='المصدر')),
                ('expected_budget', models.CharField(blank=True, max_length=80, verbose_name='الميزانية المتوقعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('first_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='أول تواصل')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تواصل')),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد المتابعة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('waiting', 'بانتظار الرد'), ('negotiating', 'تفاوض'), ('proposal_sent', 'أُرسل العرض'), ('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('long_term', 'عميل دائم'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_leads', to=settings.AUTH_USER_MODEL, verbose_name='العضو المرتبط')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('services', models.ManyToManyField(blank=True, related_name='leads', to='portfolio.service', verbose_name='الخدمات المطلوبة')),
            ],
            options={
                'verbose_name': 'عميل محتمل',
                'verbose_name_plural': 'العملاء المحتملون',
                'ordering': ['-created_at'],
                'permissions': [('export_leads', 'تصدير العملاء المحتملين')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('type', models.CharField(choices=[('call', 'مكالمة'), ('whatsapp', 'واتساب'), ('email', 'بريد'), ('meeting', 'اجتماع'), ('other', 'أخرى')], max_length=12, verbose_name='النوع')),
                ('direction', models.CharField(choices=[('inbound', 'وارد'), ('outbound', 'صادر')], default='outbound', max_length=10, verbose_name='الاتجاه')),
                ('summary', models.TextField(verbose_name='الملخص')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التواصل')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead')),
            ],
            options={
                'verbose_name': 'تواصل',
                'verbose_name_plural': 'سجل التواصل',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='الموعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'معلّقة'), ('done', 'منجزة'), ('missed', 'فائتة')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='أُرسل التذكير')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.lead')),
            ],
            options={
                'verbose_name': 'متابعة',
                'verbose_name_plural': 'المتابعات',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(verbose_name='الملاحظة')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('file', models.FileField(upload_to='crm/%Y/%m/', verbose_name='الملف')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_attachments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.lead')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('language', models.CharField(default='ar', max_length=5, verbose_name='اللغة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('read', 'مقروءة'), ('replied', 'تم الرد'), ('archived', 'مؤرشفة')], db_index=True, default='new', max_length=16, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='crm.lead', verbose_name='العميل المحتمل')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='crm.lead', verbose_name='العميل المحتمل الأصلي'),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='الرمز المرجعي')),
                ('project_type', models.CharField(choices=[('website', 'موقع'), ('mobile', 'تطبيق موبايل'), ('desktop', 'تطبيق سطح مكتب'), ('system', 'نظام إداري'), ('existing', 'تطوير نظام قائم'), ('api', 'واجهة برمجية'), ('hosting', 'استضافة'), ('consulting', 'استشارة وتحليل')], max_length=20, verbose_name='نوع المشروع')),
                ('sector', models.CharField(blank=True, max_length=20, verbose_name='القطاع')),
                ('requirements', models.JSONField(blank=True, default=dict, verbose_name='المتطلبات')),
                ('description', models.TextField(blank=True, verbose_name='وصف المشروع')),
                ('budget_range', models.CharField(blank=True, choices=[('under_500', 'أقل من 500$'), ('500_2000', '500$ – 2000$'), ('2000_5000', '2000$ – 5000$'), ('5000_10000', '5000$ – 10000$'), ('over_10000', 'أكثر من 10000$'), ('unsure', 'غير محدد')], max_length=20, verbose_name='الميزانية')),
                ('timeline', models.CharField(blank=True, choices=[('urgent', 'عاجل (أقل من شهر)'), ('short', '1 – 3 أشهر'), ('medium', '3 – 6 أشهر'), ('flexible', 'مرن')], max_length=20, verbose_name='المدة المتوقعة')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='واتساب')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='الشركة')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='المدينة')),
                ('preferred_language', models.CharField(default='ar', max_length=5, verbose_name='اللغة المفضلة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewed', 'تمت المراجعة'), ('contacted', 'تم التواصل'), ('meeting_scheduled', 'موعد محدد'), ('proposal_sent', 'أُرسل العرض'), ('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('draft', 'غير مكتمل')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(default='website_form', max_length=20, verbose_name='المصدر')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='crm.lead', verbose_name='العميل المحتمل')),
            ],
            options={
                'verbose_name': 'طلب مشروع',
                'verbose_name_plural': 'طلبات المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('file', models.FileField(upload_to='requests/%Y/%m/', verbose_name='الملف')),
                ('original_name', models.CharField(max_length=255, verbose_name='الاسم الأصلي')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='الحجم')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='نوع المحتوى')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.projectrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مرفق طلب',
                'verbose_name_plural': 'مرفقات الطلبات',
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='crm_lead_status_ef0d82_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('client__isnull', False), _connector='OR'), name='interaction_target_required'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('client__isnull', False), _connector='OR'), name='followup_target_required'),
        ),
        migrations.AddConstraint(
            model_name='crmnote',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('client__isnull', False), _connector='OR'), name='crmnote_target_required'),
        ),
        migrations.AddIndex(
            model_name='projectrequest',
            index=models.Index(fields=['status', '-created_at'], name='crm_project_status_43b9a2_idx'),
        ),
    ]
