# Generated by Django 5.1.5 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='crmattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='crmnote',
            name='content',
            field=models.TextField(blank=True, verbose_name='الملاحظة'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='الموعد'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='summary',
            field=models.TextField(blank=True, verbose_name='الملخص'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(blank=True, choices=[('call', 'مكالمة'), ('whatsapp', 'واتساب'), ('email', 'بريد'), ('meeting', 'اجتماع'), ('other', 'أخرى')], max_length=12, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'موقع'), ('mobile', 'تطبيق موبايل'), ('desktop', 'تطبيق سطح مكتب'), ('system', 'نظام إداري'), ('existing', 'تطوير نظام قائم'), ('api', 'واجهة برمجية'), ('hosting', 'استضافة'), ('consulting', 'استشارة وتحليل')], max_length=20, verbose_name='نوع المشروع'),
        ),
        migrations.AlterField(
            model_name='requestattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم الأصلي'),
        ),
    ]
