# Generated by Django 5.1.5 on 2026-09-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_name_alter_contactmessage_email_and_more'),
        ('portfolio', '0003_technology_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='portfolio.service', verbose_name='الخدمة المطلوبة'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='submission_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='معرّف الإرسال'),
        ),
    ]
