# Generated by Django 5.1.5 on 2026-09-25 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """رمز متابعة لكل سجل قائم، ورقم مرجعي للرسائل بترتيب وصولها."""
    import secrets

    ProjectRequest = apps.get_model("crm", "ProjectRequest")
    ContactMessage = apps.get_model("crm", "ContactMessage")

    for request in ProjectRequest.objects.filter(tracking_token__isnull=True).only("pk"):
        ProjectRequest.objects.filter(pk=request.pk).update(
            tracking_token=secrets.token_urlsafe(16)
        )

    counters: dict[int, int] = {}
    for message in ContactMessage.objects.order_by("created_at", "pk").only("pk", "created_at"):
        year = message.created_at.year
        counters[year] = counters.get(year, 0) + 1
        ContactMessage.objects.filter(pk=message.pk).update(
            reference_code=f"MSG-{year}-{counters[year]:04d}",
            tracking_token=secrets.token_urlsafe(16),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_request_service_and_submission_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='tracking_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='رمز المتابعة'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='tracking_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='رمز المتابعة'),
        ),
        migrations.CreateModel(
            name='ClientReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('body', models.TextField(verbose_name='نص الرد')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_replies', to=settings.AUTH_USER_MODEL, verbose_name='كاتب الرد')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crm.contactmessage', verbose_name='الرسالة')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crm.projectrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'رد على العميل',
                'verbose_name_plural': 'الردود على العملاء',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('message__isnull', True), ('request__isnull', False)), models.Q(('message__isnull', False), ('request__isnull', True)), _connector='OR'), name='clientreply_single_target')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
