# Generated by Django 5.1.5 on 2026-09-25 15:43

from django.db import migrations, models


def renumber(apps, schema_editor):
    """أرقام من خمس خانات للسجلات القائمة؛ القديم يُحفظ ويبقى مقبولًا في البحث."""
    import secrets

    ProjectRequest = apps.get_model("crm", "ProjectRequest")
    ContactMessage = apps.get_model("crm", "ContactMessage")

    used = {
        code
        for model in (ProjectRequest, ContactMessage)
        for code in model.objects.values_list("reference_code", flat=True)
        if code and code.isdigit()
    }

    def fresh() -> str:
        while True:
            candidate = str(secrets.randbelow(90000) + 10000)
            if candidate not in used:
                used.add(candidate)
                return candidate

    for model in (ProjectRequest, ContactMessage):
        for record in model.objects.order_by("created_at", "pk").only("pk", "reference_code"):
            if record.reference_code and record.reference_code.isdigit():
                continue
            model.objects.filter(pk=record.pk).update(
                legacy_reference=record.reference_code or "",
                reference_code=fresh(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_tracking_and_client_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='legacy_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, verbose_name='الرقم القديم'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='legacy_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, verbose_name='الرقم القديم'),
        ),
        migrations.RunPython(renumber, migrations.RunPython.noop),
    ]
