# Generated by Django 5.1.5 on 2026-07-30 16:43

import apps.core.models.base
import apps.media_library.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder', verbose_name='المجلد الأعلى')),
            ],
            options={
                'verbose_name': 'مجلد وسائط',
                'verbose_name_plural': 'مجلدات الوسائط',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('file', models.FileField(upload_to=apps.media_library.models.media_upload_path, verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('document', 'مستند'), ('archive', 'أرشيف'), ('video', 'فيديو')], db_index=True, default='image', max_length=16, verbose_name='النوع')),
                ('original_name', models.CharField(max_length=255, verbose_name='الاسم الأصلي')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='نوع المحتوى')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='الحجم بالبايت')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='العرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='library/thumbs/%Y/%m/', verbose_name='المصغّرة')),
                ('webp_version', models.FileField(blank=True, null=True, upload_to='library/webp/%Y/%m/', verbose_name='نسخة WebP')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('alt_ar', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (عربي)')),
                ('alt_en', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (إنجليزي)')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='مرات الاستخدام')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_library.mediafolder', verbose_name='المجلد')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', '-created_at'], name='media_libra_file_ty_12c187_idx'),
        ),
    ]
