# Generated by Django 5.1.5 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم الأصلي'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم'),
        ),
    ]
