# Generated by Django 5.1.5 on 2026-07-31 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('value', models.CharField(help_text='بريد كامل مثل spam@x.com أو نطاق مثل @spam.com', max_length=254, unique=True, verbose_name='البريد أو النطاق')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_emails', to=settings.AUTH_USER_MODEL, verbose_name='حظره')),
            ],
            options={
                'verbose_name': 'بريد محظور',
                'verbose_name_plural': 'البريد المحظور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('guest_name', models.CharField(blank=True, max_length=80, verbose_name='اسم الزائر')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الزائر')),
                ('content', models.TextField(max_length=3000, verbose_name='النص')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('spam', 'سبام')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('notify_on_reply', models.BooleanField(default=True, verbose_name='إشعار عند الرد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_comments', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='ردًا على')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='المقال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
                'permissions': [('approve_comment', 'اعتماد التعليقات')],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المبلِّغ')),
                ('reason', models.CharField(choices=[('spam', 'سبام'), ('offensive', 'مسيء'), ('off_topic', 'خارج الموضوع'), ('other', 'أخرى')], max_length=12, verbose_name='السبب')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('resolved', 'تمت المعالجة'), ('dismissed', 'مرفوض')], db_index=True, default='open', max_length=12, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment', verbose_name='التعليق')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلِّغ')),
            ],
            options={
                'verbose_name': 'بلاغ تعليق',
                'verbose_name_plural': 'بلاغات التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'status', 'created_at'], name='comments_co_post_id_c397d3_idx'),
        ),
    ]
