# Generated by Django 5.1.5 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedemail',
            name='value',
            field=models.CharField(blank=True, help_text='بريد كامل مثل spam@x.com أو نطاق مثل @spam.com', max_length=254, unique=True, verbose_name='البريد أو النطاق'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=3000, verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reason',
            field=models.CharField(blank=True, choices=[('spam', 'سبام'), ('offensive', 'مسيء'), ('off_topic', 'خارج الموضوع'), ('other', 'أخرى')], max_length=12, verbose_name='السبب'),
        ),
    ]
