# Generated by Django 5.1.5 on 2026-09-15 06:52

import apps.core.models.base
import apps.newsletter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_alter_mediafile_original_name_alter_mediafolder_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مُفعّل')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='المفتاح')),
                ('subject_ar', models.CharField(blank=True, max_length=200, verbose_name='الموضوع الافتراضي (عربي)')),
                ('subject_en', models.CharField(blank=True, max_length=200, verbose_name='الموضوع الافتراضي (إنجليزي)')),
                ('html_ar', models.TextField(blank=True, verbose_name='HTML (عربي)')),
                ('html_en', models.TextField(blank=True, verbose_name='HTML (إنجليزي)')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='المتغيرات')),
            ],
            options={
                'verbose_name': 'قالب بريد',
                'verbose_name_plural': 'قوالب البريد',
                'ordering': ['name'],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب')),
                ('key', models.SlugField(max_length=40, unique=True, verbose_name='المفتاح')),
                ('name_ar', models.CharField(max_length=80, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.CharField(blank=True, max_length=200, verbose_name='الوصف (عربي)')),
                ('description_en', models.CharField(blank=True, max_length=200, verbose_name='الوصف (إنجليزي)')),
            ],
            options={
                'verbose_name': 'اهتمام',
                'verbose_name_plural': 'الاهتمامات',
                'ordering': ['display_order', 'key'],
            },
            bases=(apps.core.models.base.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=160, verbose_name='الاسم الداخلي')),
                ('subject_ar', models.CharField(blank=True, max_length=200, verbose_name='الموضوع (عربي)')),
                ('subject_en', models.CharField(blank=True, max_length=200, verbose_name='الموضوع (إنجليزي)')),
                ('content_ar', models.TextField(blank=True, verbose_name='المحتوى (عربي)')),
                ('content_en', models.TextField(blank=True, verbose_name='المحتوى (إنجليزي)')),
                ('cta_label_ar', models.CharField(blank=True, max_length=80, verbose_name='نص الزر (عربي)')),
                ('cta_label_en', models.CharField(blank=True, max_length=80, verbose_name='نص الزر (إنجليزي)')),
                ('cta_url', models.URLField(blank=True, verbose_name='رابط الزر')),
                ('target_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية'), ('all', 'الكل')], default='all', max_length=3, verbose_name='اللغة المستهدفة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('sending', 'قيد الإرسال'), ('sent', 'أُرسلت'), ('failed', 'فشلت'), ('cancelled', 'أُلغيت')], db_index=True, default='draft', max_length=10, verbose_name='الحالة')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد الإرسال')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمال الإرسال')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط إرسال')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='إجمالي المستلمين')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='أُرسل')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='فشل')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='فتح')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='نقر')),
                ('unsubscribe_count', models.PositiveIntegerField(default=0, verbose_name='إلغاء اشتراك')),
                ('source_model', models.CharField(blank=True, max_length=32, verbose_name='نموذج المصدر')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف المصدر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediafile', verbose_name='الصورة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّله')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='newsletter.emailtemplate', verbose_name='القالب')),
                ('target_interests', models.ManyToManyField(blank=True, help_text='فارغ = كل المشتركين النشطين', related_name='campaigns', to='newsletter.interest', verbose_name='الاهتمامات المستهدفة')),
            ],
            options={
                'verbose_name': 'حملة',
                'verbose_name_plural': 'الحملات',
                'ordering': ['-created_at'],
                'permissions': [('send_campaign', 'إرسال الحملات')],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='الاسم')),
                ('language', models.CharField(db_index=True, default='ar', max_length=2, verbose_name='اللغة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('active', 'نشط'), ('unsubscribed', 'ألغى الاشتراك'), ('bounced', 'مرتد'), ('complained', 'اشتكى')], db_index=True, default='pending', max_length=14, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('footer', 'التذييل'), ('home', 'الرئيسية'), ('blog_post', 'مقال'), ('popup', 'نافذة منبثقة'), ('manual', 'يدوي'), ('member_signup', 'تسجيل عضو'), ('member_area', 'صفحة العضو')], default='home', max_length=16, verbose_name='المصدر')),
                ('confirm_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='رمز التأكيد')),
                ('confirm_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال للتأكيد')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('unsubscribe_token', models.CharField(default=apps.newsletter.models._token, max_length=64, unique=True, verbose_name='رمز إلغاء الاشتراك')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الموافقة')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('interests', models.ManyToManyField(blank=True, related_name='subscribers', to='newsletter.interest', verbose_name='الاهتمامات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['-created_at'],
                'permissions': [('export_subscribers', 'تصدير المشتركين')],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.newsletter.models._token, max_length=64, unique=True, verbose_name='رمز التتبع')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('sent', 'أُرسل'), ('failed', 'فشل'), ('bounced', 'مرتد')], db_index=True, default='pending', max_length=8, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='رسالة الخطأ')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='أول فتح')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='أول نقر')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='newsletter.campaign', verbose_name='الحملة')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='newsletter.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'مستلم حملة',
                'verbose_name_plural': 'مستلمو الحملات',
            },
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['status', 'language'], name='newsletter__status_03a97c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='newsletter__campaig_da95e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'subscriber'), name='uniq_campaign_subscriber'),
        ),
    ]
